# Generated by Django 3.2.23 on 2024-01-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240118_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='closure',
            field=models.CharField(blank=True, default=0, max_length=32),
        ),
        migrations.DeleteModel(
            name='Closure',
        ),
    ]
