# Generated by Django 3.2.23 on 2024-01-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240118_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closure',
            options={'verbose_name_plural': 'Closure'},
        ),
    ]
