# Generated by Django 3.2.23 on 2024-03-02 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vintage',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Enter year in YYYY format', regex='^.{4}$')]),
        ),
    ]
