# Generated by Django 3.2.23 on 2024-03-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_grape_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
